config/routes.rb
Rails.application.routes.draw do

  resources :recipes

  root 'recipes#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  has_attached_file :image, styles: { :small => "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :find_recipe, only: [:show, :edit, :update, :destroy]
	
	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
	end

	def new
		@recipe = Recipe.new
	end 

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to @recipe, notice: "Succesfully created new recipe"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def destroy
		@recipe.destroy
		redirect_to root_path, notice: "Succesfully deleted recipe"
	end

	private 

	def recipe_params
		params.require(:recipe).permit(:title, :description, :image)
	end


	def find_recipe
		@recipe = Recipe.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<i class='fa fa-glass'></i> Smoothies".html_safe, root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Recipe", new_recipe_path %></li>
        <li><%= link_to "Sign Out", root_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smoothies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
	<% flash.each do |name, msg| %>
	<%= content_tag :div, msg, class: "alert" %>
	<% end %>

<%= yield %>

</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>
<% if @recipe.errors.any? %>
	<div id="errors">
		<p>
			<%= @recipe.errors.count %>
			Prevented this recipe from saving
		</p>
	<ul>
		<% @recipe.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="panel-body">
	<%= f.input :title, input_html: { class: 'form-control'} %>
	<%= f.input :description, input_html: { class: 'form-control'} %>
	<%= f.input :image, input_html: { class: 'form-control'} %>

</div>

<%= f.button :submit, class: "btn btn-primary" %>

<% end %>

app/views/recipes/edit.html.erb
<p>edit<p>

<%= render 'form' %>

<%= link_to "Back", root_path, class: "btn btn-primary" %>

app/views/recipes/index.html.erb
<div class="row">
	 <% recipes.each do |recipe| %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading"><h3><%= link_to recipe.title, recipe %></h3></div>
            <div class="panel-body"><%= link_to recipe do %>
              <%= image_tag recipe.image.url(:small) %>
            <% end %>
            </div>
          </div>
        </div>
        <% end %>
       <% end %>
 </div>

app/views/recipes/new.html.erb
<h2>New recipe</h2>

<%= render 'form' %>

<br/>

<%= link_to "back", root_path, class: 'btn btn-default' %>

app/views/recipes/show.html.erb
<p>Show</p>

<%= image_tag @recipe.image.url(:small) %>

<h1><%= @recipe.title %></h1>
<h3><%= @recipe.description %></h3>


<%= link_to "Back", root_path, class: "btn btn-primary" %>
<%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
<%= link_to "Delete", recipe_path, method: :delete, data: { confirm: "Are you sure?" },class: "btn btn-default" %>